server:
    port: 8080
    error:
        include-message: always

spring:
    main:
        web-application-type: servlet
    data:
        mongodb:
            uri: mongodb+srv://alicesin:9LBG9jHrZWvNZnlR@cluster0.jj3jwct.mongodb.net/test
            auto-index-creation: true
